language: ruby

sudo: false
cache: bundler

before_install:
  - gem install bundler

before_script:
  - bundle exec jbundle install

script: 'bundle exec rake test:ci:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'

rvm:
  - jruby-1.7.20

gemfile:
  - Gemfile

jdk:
  - openjdk8
